[package]
name = "vetis-server"
version = "0.1.0"
authors = ["Rogerio Araújo <rogerio.araujo@gmail.com>"]
edition = "2024"
repository = "https://github.com/vetis-server/vetis-tokio"
homepage = "https://github.com/vetis-server/vetis"
description = "Very Tiny Server"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["http", "networking", "tokio", "web-server"]
publish = true
rust-version = "1.85.0"

[features]
default = ["yaml-config", "logging", "static", "flash"]

# Config files support
yaml-config = ["dep:serde_yaml_ng"]
toml-config = ["dep:toml"]

logging = ["dep:vetis-log", "dep:logforth"]
metrics = ["dep:vetis-otel"]

# Script support
rhai-script = ["dep:vetis-rhai"]

# Misc modules
flash = ["dep:vetis-flash"]
proxy = ["dep:vetis-proxy"]
rev-proxy = ["dep:vetis-rev-proxy"]
static = ["dep:vetis-static"]

[dependencies]
clap = { version = "4.6.7", default-features = false, features = [
  "std",
  "derive",
] }
log = "0.4.34"
logforth = { version = "0.30.1", optional = true, features = ["starter-log"] }
mimalloc = "0.1.52"
regex = "1.13.1"
serde = "1.0.228"
serde_yaml_ng = { version = "0.10.0", optional = true }
sysinfo = { version = "0.39.6", optional = true }
toml = {version = "1.1.6", optional = true }
tokio = { version = "1.53.1", features = [
  "fs",
  "signal",
  "net",
  "macros",
  "rt-multi-thread",
  "windows-sys"
], default-features = false }

vetis = { path = "../vetis/vetis" }
#vetis = { version = "0.1.7-beta.4", default-features = false }

vetis-tokio = { path = "../vetis-tokio", features = ["http2", "http3"] }
#vetis-tokio = { version = "0.1.2-beta.5" }

vetis-flash = { path = "../vetis-extras/vetis-flash", optional = true, features = [
  "runtime-tokio",
] }
# vetis-flash = { path = "../vetis-extras/vetis-flash", optional = true, features = [
#   "runtime-tokio",
# ] }

vetis-log = { path = "../vetis-extras/vetis-log", optional = true }
#vetis-log = { path = "../vetis-extras/vetis-log", optional = true }

vetis-otel = { path = "../vetis-extras/vetis-otel", optional = true }
#vetis-otel = { path = "../vetis-extras/vetis-otel", optional = true }

vetis-proxy = { path = "../vetis-extras/vetis-proxy", optional = true, features = [
  "runtime-tokio",
] }
# vetis-proxy = { path = "../vetis-extras/vetis-proxy", optional = true, features = [
#   "runtime-tokio",
# ] }

vetis-rhai = { path = "../vetis-extras/vetis-rhai", optional = true, features = [
  "runtime-tokio",
] }
# vetis-rhai = { path = "../vetis-extras/vetis-rhai", optional = true, features = [
#   "runtime-tokio",
# ] }

vetis-rev-proxy = { path = "../vetis-extras/vetis-rev-proxy", optional = true, features = [
  "runtime-tokio",
] }
# vetis-rev-proxy = { path = "../vetis-extras/vetis-rev-proxy", optional = true, features = [
#   "runtime-tokio",
# ] }

vetis-static = { path = "../vetis-extras/vetis-static", optional = true, features = [
  "runtime-tokio",
] }
# vetis-static = { path = "../vetis-extras/vetis-static", optional = true, features = [
#   "runtime-tokio",
# ] }

[dev-dependencies]
caramelo = "0.1.5"
#deboa = { path = "../deboa/deboa" }
deboa = { version = "0.1.5-beta.2" }
# deboa-tokio = { path = "../deboa-tokio/deboa-tokio", default-features = false, features = [
#   "http2",
#   #"http3",
#   "rust-tls",
#   "default-rustls-provider",
#   "default-rustls-verifier",
# ] }
deboa-tokio = { version = "0.1.4-beta.3", default-features = false, features = [
  "http2",
  #"http3",
  "rust-tls",
  "default-rustls-provider",
  "default-rustls-verifier",
] }
tokio = { version = "1.52.3", default-features = false, features = [
  "macros",
  "rt-multi-thread",
] }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
