worker_threads = 24
max_blocking_threads = 120

[server]
enable_logging = true

[[server.listeners]]
interface = "0.0.0.0"
port = 8443
protos = ["HTTP/2.0"]
alpn_protos = ["H2"]
allow_unsafe_conn = false

[[server.hosts]]
hostname = "localhost"
root_directory = "sites/default"
enable_hsts = false
bind_addresses = [["0.0.0.0", 8443]]

[server.hosts.security]
ca_file = "certs/ca.der"
cert_file = "certs/server.der"
key_file = "certs/server.key.der"

[server.hosts.error_pages]
404 = "404.html"

[[server.hosts.paths]]
type = "static_path"
uri = "/"
directory = "html"
extensions = "\\.(html)$"
index_files = ["index.html"]

[server.hosts.paths.cache]
max_file_size = 10485760
ttl = "5m"
tti = "2m"
capacity = 1000

[[server.hosts.paths]]
type = "flash_path"
uri = "/vetis"
response = "Hello from VeTiS!"
status_code = 200

[[server.hosts.paths]]
type = "flash_path"
uri = "/vetis/rio"
response = "Fala galera!"
status_code = 200
