worker_threads = 12
max_blocking_threads = 256

[server]
workers = 1

[[server.log]]
dest = "stdout"
log_level = "INFO"

[[server.hosts]]
hostname = "bgqew-168-197-115-224.run.pinggy-free.link"
root_directory = "sites/default"
enable_hsts = false
bind_addresses = [["127.0.0.1", 8443]]
protos = ["HTTP/1.1"]
allow_unsafe_conn = true

[server.hosts.tls]
ca_file = "certs/ca.der"
cert_file = "certs/server.der"
key_file = "certs/server.key.der"
#supported_alpns = ["HTTP11"]

[server.hosts.status_pages]
404 = "html/404.html"

[[server.hosts.paths]]
type = "static"
uri = "/"
directory = "html"
extensions = "\\.(html|ico|css)$"
index_files = ["index.html"]

[server.hosts.paths.cache]
max_file_size = 10485760
ttl = "5m"
tti = "2m"
capacity = 1000

[[server.hosts.paths]]
type = "flash"
uri = "/vetis"
response = "Hello from VeTiS!"
status_code = 200

[[server.hosts.paths]]
type = "flash"
uri = "/vetis/rio"
response = "Fala galera!"
status_code = 200
